/**
 * Search Gunpla image filenames by keywords and return full CDN URLs
 */
export function searchGunplaImagesByKeywords(keywords: string[]): string[] {
  const lowerKeywords = keywords.map(k => k.toLowerCase());
  return ALL_GUNPLA_IMAGE_FILENAMES
    .filter(name => lowerKeywords.length > 0 && lowerKeywords.every(k => name.toLowerCase().includes(k)))
    .map(name => `https://cdn.gunpladb.net/${name}`);
}

import { GunplaDBResponse, GundamGrade } from '@/types/gundam';

// List of all Gunpla image filenames (add more as needed)
export const ALL_GUNPLA_IMAGE_FILENAMES = [
  "100-RX-78F00-GUNDAM-CLEAR-COLOR.jpg",
  "1100MSGW-1XXXG01WWingGundam.jpg",
  "1100MSGW-2XXXG01SShenlongGundam.jpg",
  "1100MSGW-3XXXG01DGundamDeathscythe.jpg",
  "1100MSGW-4XXXG00W0WingGundam0.jpg",
  "1100MSGW-5OZ13MSGundamEpyon.jpg",
  "1100MSGW-6XXXG01S2AltronGundam.jpg",
  "1100MSGW-7XXXG01D2GundamDeathscytheH.jpg",
  "144-rx-78f00-gundam-clear-color.jpg",
  "1_100 rx-78f00 gunndam front.jpg",
  "445076893_1011546373868277_910863186132102067_n.jpg",
  "AGAGE-01AGE1GundamAGE1Normal.jpg",
  "AGAGE-02ovvfGafran.jpg",
  "AGAGE-03RGEB790Genoace.jpg",
  "AGAGE-04RGEB790CWGenoaceCustom.jpg",
  "AGAGE-05AGE1TGundamAGE1Titus.jpg",
  "AGAGE-06xvvxcZedas.jpg",
  "AGAGE-07AGE1SGundamAGE1Spallow.jpg",
  "AGAGE-08WMSGEX1GExes.jpg",
  "AGAGE-09AGE2GundamAGE2Normal.jpg",
  "AGAGE-10RGEG1100Adele.jpg",
  "AGAGE-11RGEB890GenoaceII.jpg",
  "AGAGE-12xvmzgcZeydra.jpg",
  "AGAGE-13WMSGB5GBouncer.jpg",
  "AGAGE-14XvmdgcKhronos.jpg",
  "AGAGE-15AGE2DBGundamAGE2DoubleBullet.jpg",
  "AGAGE-16ovmeDorado.jpg",
  "AGAGE-17AGE3GundamAGE3Normal.jpg",
  "AGAGE-18xvtzgcGhirarga.jpg",
  "AGAGE-19AGE3OGundamAGE3Orbital.jpg",
  "AGAGE-20AGE3FGundamAGE3Fortress.jpg",
  "AGAGE-21AGE2DHGundamAGE2DarkHound.jpg",
  "AGAGE-22BMS004GExesJackedge.jpg",
  "AGAGE-23xvmfzcGundamLegilis.jpg",
  "AGAGE-24AGEFXGundamAGEFX.jpg",
  "amazing-barbatos-lupus.jpg",
  "AWGX-01GX9900GundamX.jpg",
  "AWGX-02GW9800GundamAirmaster.jpg",
  "AWGX-03GT9600GundamLeopard.jpg",
  "AWGX-04GX9900DVGundamXDivider.jpg",
  "AWGX-05NRX0013GundamVirsago.jpg",
  "AWGX-06GX9901DXGundamDoubleX.jpg",
  "AWGX-07GW9800BGundamAirmasterBurst.jpg",
  "AWGX-08GFalconUnitDoubleX.jpg",
  "AWGX-09GT9600DGundamLeopardDestroy.jpg",
  "black-knight-triple-set.jpg",
  "black-tri-stars-zaku-mg.jpg",
  "calibarn-permet-score-5.jpg",
  "dark-dagger-L.jpg",
  "duel-blitz.jpg",
  "EG-1GN000000Gundam.jpg",
  "EG-2GATX105StrikeGundam.jpg",
  "EG-2GN001GundamExia.jpg",
  "EG-3RX782Gundam.jpg",
  "EG-3RX93?Gundam.jpg",
  "EG-4GATX105StrikeGundam.jpg",
  "EG-GATX105AQMEX04GunbarrelStrikeGundamGundamBreakerVer.jpg",
  "EG-MBF02StrikeRouge.jpg",
  "EG-NARoundBoxwithGunplaRX782GundamChristmasColor.jpg",
  "EG-NARoundBoxwithGunplaRX782GundamSnowImageColor.jpg",
  "EG-NARX782GundamClearBlue.jpg",
  "EG-NARX782GundamClearRed.jpg",
  "EG-NARX782GundamClearYellow.jpg",
  "EG-NARX782GundamLitePackageVer.jpg",
  "EG-NARX782GundamPaintingModel.jpg",
  "EG-OptionPartsSetGunpla14GunbarrelStriker.jpg",
  "EG-RX93nuGundamPsychoframeLuminousImageColor.jpg",
  "engage-gundam.jpg",
  "EX-12LuggunSealanth.jpg",
  "EX-15GundamSEEDMechaSet1.jpg",
  "EX-16MobileShipAlbion.jpg",
  "EX-18MobileShipArgama.jpg",
  "EX-19ArchAngel.jpg",
  "EX-1GundamTrailerTruck.jpg",
  "EX-20Musai.jpg",
  "EX-21FFMHY101Eternal.jpg",
  "EX-22MobileArmorExass.jpg",
  "EX-23SalamisMagellan.jpg",
  "EX-26LHMBB01Minerva.jpg",
  "EX-28MagellaAttack.jpg",
  "EX-29SamsonTrailer.jpg",
  "EX-2Dodaitwo.jpg",
  "EX-30LaVieenRose.jpg",
  "EX-31SCV70WhiteBase.jpg",
  "EX-34YMT05Hildolfr.jpg",
  "EX-35MP02AOggo.jpg",
  "EX-4DoppFighter.jpg",
  "EX-5SGundamAttacker.jpg",
  "EX-7JetCoreBooster.jpg",
  "EX-8GarmasDopp.jpg",
  "EX-9Gunperry.jpg",
  "EX-NAArchAngelLimitedEdition.jpg",
  "EX-NAFFMHY101EternalLimitededition.jpg",
  "EX-NAMobileShipAlbionLimitedEdition.jpg",
  "EX-NAMobileShipArgamaLimitedEdition.jpg",
  "f90-1F90GundamF90ADSType.jpg",
  "f90-2F90GundamF90PType.jpg",
  "f90-3F90GundamF90VType.jpg",
  "f90-4F90IIGundamF90IILType.jpg",
  "f90-n-type.jpg",
  "f91-1RGM111Hardygun.jpg",
  "f91-2RXF91GundamRXF91.jpg",
  "f91-3XM07GVignaZirah.jpg",
  "f91-4F71BGCannonMagna.jpg",
  "f91-5RX99NeoGundam.jpg",
  "f91-6RXF91AGundamRXF91Kai.jpg",
  "f91-7F90IIIYClusterGundam.jpg",
  "FG-01GN001GundamExia.jpg",
  "FG-01RX782Gundam.jpg",
  "FG-02GN002GundamDynames.jpg",
  "FG-02MS06SZakuIICharAznableCustom.jpg",
  "FG-03GN003GundamKyrios.jpg",
  "FG-03MS06FZakuII.jpg",
  "FG-04GN005GundamVirtue.jpg",
  "FG-1961GArmor.jpg",
  "FG-NAGN0000Gundam.jpg",
  "FG-NAGN001GundamExiaRollOutColorVer.jpg",
  "FG-NARX782GundamJREastE235SeriesVer.jpg",
  "FG-RX782GUNDAM2024.jpg",
  "FG-RX78FRGMTGundam.jpg",
  "filelist.txt",
  "fm-aerial-permet-score-six.jpg",
  "Full-Mechanics-001GATX131CalamityGundam.jpg",
  "Full-Mechanics-002GATX370RaiderGundam.jpg",
  "Full-Mechanics-003XVX016GundamAerial.jpg",
  "Full-Mechanics-NAGATX130AileCalamityGundam.jpg",
  "Full-Mechanics-NAZGMFX10AFreedomGundamVerGCP.jpg",
  "GGMS-10NRX0013CBGundamVirsagoChestBreak.jpg",
  "GGMS-1GX9900GundamX.jpg",
  "GGMS-2GW9800GundamAirmaster.jpg",
  "GGMS-3GT9600GundamLeopard.jpg",
  "GGMS-4NRX0013GundamVirsago.jpg",
  "GGMS-5NRX0015GundamAshtaron.jpg",
  "GGMS-6GX9900DVGundamXDivider.jpg",
  "GGMS-7GX9901DXGundamDoubleX.jpg",
  "GGMS-8GW9800BGundamAirmasterBurst.jpg",
  "GGMS-9GT9600DGundamLeopardDestroy.jpg",
  "gmIII_axis color_.jpg",
  "gundnode.jpg",
  "heingra.jpg",
  "HG-06MSSR2LeoR.jpg",
  "HG-2023GUNDAMCALIBARN.jpg",
  "HG-AMS123XVarguil.jpg",
  "HG-AMX014RREBENWOLFAOZReBootVer.jpg",
  "HG-AMX101GallussJ.jpg",
  "HG-ASNGXXGundamVidar.jpg",
  "HG-BeguirBeuTorche.jpg",
  "hg-destiny-spec-ii.jpg",
  "HG-DZ001DeltaZayin.jpg",
  "HG-GF13011NCDragonGundam.jpg",
  "HG-GFAS-X1-DESTROY-GUNDAM.jpg",
  "HG-gMS01BocatasGelgoog.jpg",
  "HG-gMS01SugaisGelgoog.jpg",
  "HG-gMSaRedGundam.jpg",
  "HG-gMSKGFreD.jpg",
  "HG-GQuuuuuuX.jpg",
  "HG-MD0021Desulator.jpg",
  "HG-Me02RF01MesserTypeF01ClearColor.jpg",
  "HG-Medd.jpg",
  "HG-MRX010PsychoGundamMkII.jpg",
  "HG-MS06DZakuDesertTypePinkPantherCorps.jpg",
  "HG-MS06FZakuIISolari(RequiemforVengeance).jpg",
  "HG-MS06R1AZAKUIIHighMobilityType.jpg",
  "HG-MS06SSPPoliceZaku.jpg",
  "HG-MS15HXaviersGyanHakujiPacks.jpg",
  "HG-MSN06SSinanjuVerGSF.jpg",
  "HG-MWS19051GDGundamFirst.jpg",
  "HG-NOGM2D1EBlackKnightSquadCalreA.jpg",
  "HG-OptionPartsSetGunPla15CavalierAifrid.jpg",
  "HG-OZ06MSSN3LeoN.jpg",
  "HG-PMX002BolinoakSammahn.jpg",
  "HG-RGM79LightTypeGuncannon.jpg",
  "HG-RGM79LVGM NightSeekerII.jpg",
  "HG-RH35ERiah35DrakenE.jpg",
  "hg-rising-freedom-clear.jpg",
  "HG-RisingFreedomGundamRecirculationColorNeonYellow.jpg",
  "HG-RX78(G)EGundamEX(RequiemforVengeance).jpg",
  "HG-RX7801FSDGundamFSDwithPrototypeLongRangeBeamRifle.jpg",
  "HG-RX782GundamJALOriginalColorVer.jpg",
  "HG-RX78F00E.jpg",
  "HG-RX78F00EGundam.jpg",
  "HG-STTS909RisingFreedomGundamRecirculationColorNeonYellow.jpg",
  "HG-STTSF400MurasameKai.jpg",
  "HG-TR6Barzam IIReZeonCapturedAOZReBootver.jpg",
  "HG-XMXXGhostGundam.jpg",
  "HG-XXXG01S2AltronGundam.jpg",
  "HG-YG111GSelfPerfectPackReconguistainGtheMovieVer.jpg",
  "HG-ZAKU-HIGH-MOBILITY-SURFACE-TYPE-SANHO.jpg",
  "HG-ZakuIIFtypeChubsandKale's+UnidentifiedZakuIISolarisPartsSetRFV.jpg",
  "HG-ZGMF2027AHildaGYANStrom.jpg",
  "HG-ZGMFA24S2AGXQ754V2DestinyGundamSpecIIZeusSilhouette.jpg",
  "HG-ZGMFA262PDPMightyStrikeFreedomGundamClearColor.jpg",
  "HG-ZGMFMM07ZGokGundamSEEDFreedomver.jpg",
  "HG08thmsteam-1RX79GGundamvsMS06JZakuII.jpg",
  "HG08thmsteam-2RGM79GGM.jpg",
  "HG08thmsteam-3RX79GEz8GundamEz8.jpg",
  "HG08thmsteam-4MS06JZakuII.jpg",
  "HG08thmsteam-5MS07B3GoufCustom.jpg",
  "HG08thmsteam-6MS07H8GoufFlightType.jpg",
  "HG08thmsteam-7RGM79GGMSniper.jpg",
  "HG08thmsteam-NA20thBirthdayLimitedGundamRX79.jpg",
  "HG144gunplabuilders-01GPBX80BeginningGundam.jpg",
  "HG144gunplabuilders-02RX93?2Hi?GundamGPBcolor.jpg",
  "HG144gunplabuilders-03GPB06FSuperCustomZakuF2000.jpg",
  "HG144gunplabuilders-04GPB04BBeargguy.jpg",
  "HG144gunplabuilders-05GPBX7830ForeverGundam.jpg",
  "HG144gunplabuilders-06GPBX8030FBeginning30Gundam.jpg",
  "HG144gunplabuilders-07GPBX80JBeginningJGundam.jpg",
  "HG144gunplabuilders-08GPBX80DBeginningDGundam.jpg",
  "HG144gunplabuilders-NAAMX107BawooGPBColorMS05LZakuISniperTypeGPBColor.jpg",
  "HG144gunplabuilders-NAGPB04BBeargguy7ElevenColorVer.jpg",
  "HG144gunplabuilders-NAGPBX7830ForeverGundamGPBDColorSakiMishimaVerActionBase3Blue.jpg",
  "HG144gunplabuilders-NAGPBX8030FBeginning30GundamGPBJColorClearIFSVerActionBase3Red.jpg",
  "HG144gunplabuilders-NAMSN00100HyakuShikiGPBColorByakuShiki.jpg",
  "HG144gunplabuilders-NAMSN04SazabiGPBColor.jpg",
  "HG144gunplabuilders-NAPinkBeargguy.jpg",
  "HG1990-01RX78Gundam.jpg",
  "HG1990-02MSZ006ZetaGundam.jpg",
  "HG1990-03RX178GundamMkII.jpg",
  "HG1990-04MSZ010ZZGundam.jpg",
  "HG1990-362HyperMegaLauncherforMSZ006ZetaGundam.jpg",
  "HG1990-393MSZ006ZetaGundamWaveRiderConversionParts.jpg",
  "HG1990-GS01GSAVIOURGSaviourSpaceMode.jpg",
  "hgac-burnlapius-box-art.jpg",
  "HGBeyondGlobal-RX782GundamBeyondGlobal.jpg",
  "HGBeyondGlobal-RX782GundamBeyondGlobalClearColor.jpg",
  "HGBeyondGlobal-RX782GundamBeyondGlobalTheGundamBaseColor.jpg",
  "HGBeyondGlobal-RX783G3GundamBeyondGlobal.jpg",
  "HGBuildDivers-000GN0000DVRGundam00Diver.jpg",
  "HGBuildDivers-001AGEIIMGGundamAGEIIMagnum.jpg",
  "HGBuildDivers-002RGM86RBMGMIIIBeamMaster.jpg",
  "HGBuildDivers-003GH001RBGrimoireRedBeret.jpg",
  "HGBuildDivers-004PEN01MMomokapool.jpg",
  "HGBuildDivers-005GNX803OGOgreGNX.jpg",
  "HGBuildDivers-006GN1001NSeraveeGundamScheherazade.jpg",
  "HGBuildDivers-007xvtmmcGearaGhirarga.jpg",
  "HGBuildDivers-008OZ06MSMPDLeoNPD.jpg",
  "HGBuildDivers-009GN0000DVRAGundam00DiverAce.jpg",
  "HGBuildDivers-010RMS117G11GalbaldyRebake.jpg",
  "HGBuildDivers-011XXXG01S2???GundamJiyanAltron.jpg",
  "HGBuildDivers-012MBFPNNGundamAstrayNoName.jpg",
  "HGBuildDivers-013RX?RXZeromaru.jpg",
  "HGBuildDivers-014SPGN0000DVRSGundam00SkyHigherThanSkyPhase.jpg",
  "HGBuildDivers-015RGM89BMJeganBlastMaster.jpg",
  "HGBuildDivers-016DiverNami.jpg",
  "HGBuildDivers-017AGMFX56SaImpulseGundamArc.jpg",
  "HGBuildDivers-018AGMFX56SlImpulseGundamLancier.jpg",
  "HGBuildDivers-019ZGMFX20ALPGundamLovePhantom.jpg",
  "HGBuildDivers-020GBNGF01GBNGuardFrame.jpg",
  "HGBuildDivers-021GN0000DVRSHWSGundam00SkyHWSTransAmInfinityMode.jpg",
  "HGBuildDivers-022GF13017NJBGundamShiningBreak.jpg",
  "HGBuildDivers-023HERSELFMobileDollSarah.jpg",
  "HGBuildDivers-024AGEIIMGSVGundamAGEIIMagnumSVver.jpg",
  "HGBuildDivers-025GBNGFRX78GBNBaseGundam.jpg",
  "HGBuildDivers-026RX???RXZeromaruShinkiKessho.jpg",
  "HGBuildDivers-027GN011ZGundamZerachiel.jpg",
  "HGBuildDivers-028DiverAyame.jpg",
  "HGBuildDivers-NAAGEIIMGGundamAGEIIMagnumClearColor.jpg",
  "HGBuildDivers-NAAGEIIMGGundamAGEIIMagnumDiveIntoDimensionClear.jpg",
  "HGBuildDivers-NAAGEIIMGSVGundamAGEIIMagnumSVverFXPlosion.jpg",
  "HGBuildDivers-NADiverAyameGundamBaseColorPetitgguySet.jpg",
  "HGBuildDivers-NAGF13017NJBGundamShiningBreakBefore.jpg",
  "HGBuildDivers-NAGN0000DVRAGundam00DiverAceGoldCoating.jpg",
  "HGBuildDivers-NAGN0000DVRAGundam00DiverAceSpecialCoating.jpg",
  "HGBuildDivers-NAGN0000DVRGundam00DiverDiveIntoDimensionClear.jpg",
  "HGBuildDivers-NAGN0000DVRGundam00DiverGoldenDiveSparkle.jpg",
  "HGBuildDivers-NAGN0000DVRGundam00DiverTransAmClear.jpg",
  "HGBuildDivers-NAGN0000DVRSGundam00SkyDiveIntoDimensionClear.jpg",
  "HGBuildDivers-NAHERSELFMobileDollSarahMirrorMissionVer.jpg",
  "HGBuildDivers-NARMS099BCBuildâGundam.jpg",
  "HGBuildDivers-NARX?RXZeromaruShishiku.jpg",
  "HGBuildDivers-NAYGIIIGundamGElseBefore.jpg",
  "HGBuildDiversrerise-001PFFX7E3EarthreeGundam.jpg",
  "HGBuildDiversrerise-002VeetwoWeapons.jpg",
  "HGBuildDiversrerise-003MarsfourWeapons.jpg",
  "HGBuildDiversrerise-004ZGMFX19AKGundamJusticeKnight.jpg",
  "HGBuildDiversrerise-007Valkylander.jpg",
  "HGBuildDiversrerise-008PFFX7CoreGundamRealTypeColorMarsfourUnit.jpg",
  "HGBuildDiversrerise-009MSF007SSGundamSeltsam.jpg",
  "HGBuildDiversrerise-010InjusticeWeapons.jpg",
  "HGBuildDiversrerise-011JDG009XELBEldoraBrute.jpg",
  "HGBuildDiversrerise-013PFFX7J5JupitiveGundam.jpg",
  "HGBuildDiversrerise-014HERSELFMobileDollMay.jpg",
  "HGBuildDiversrerise-016MSF007TEGundamTertium.jpg",
  "HGBuildDiversrerise-017MercuoneUnit.jpg",
  "HGBuildDiversrerise-019MercuoneWeapons.jpg",
  "HGBuildDiversrerise-020YGIIIGundamGElse.jpg",
  "HGBuildDiversrerise-022AGPX1E3AlusEarthreeGundam.jpg",
  "HGBuildDiversrerise-023PFFX7IIU7UravenGundam.jpg",
  "HGBuildDiversrerise-025SaturnixWeapons.jpg",
  "HGBuildDiversrerise-027AGETRYMAGGundamTRYAGEMagnum.jpg",
  "HGBuildDiversrerise-028JMA0530MAYWodomPod.jpg",
  "HGBuildDiversrerise-029Fake?Unit.jpg",
  "HGBuildDiversrerise-030Fake?Weapons.jpg",
  "HGBuildDiversrerise-031NepteightUnit.jpg",
  "HGBuildDiversrerise-033GATX303KGundamAegisKnight.jpg",
  "HGBuildDiversrerise-034PFFX7RANIMAGundamAnimaRize.jpg",
  "HGBuildDiversrerise-035AunRizeArmor.jpg",
  "HGBuildDiversrerise-037PFFX7IIBUILDDiVERSReRisingGundam.jpg",
  "HGBuildDiversrerise-038MHF01DRLoadAstrayDoubleRebake.jpg",
  "HGBuildDiversrerise-039GN0000DVRSMGundam00SkyMoebius.jpg",
  "HGBuildDiversrerise-041TRYSlashBlade.jpg",
  "HGBuildDiversrerise-042PFFX7IICoreGundamIIG3Color.jpg",
  "HGBuildDiversrerise-043PFFX7IICoreGundamIITitansColor.jpg",
  "HGBuildDiversrerise-NADT6800ELEldoraDaughtress.jpg",
  "HGBuildDiversrerise-NAHERSELFMobileDollMayTheGundamBaseColor.jpg",
  "HGBuildDiversrerise-NAPFFX7CoreGundamPFFX7IICoreGundamIIAGPX1AlusCoreGundamLowVisibilityVer.jpg",
  "HGBuildDiversrerise-NAPFFX7CoreGundamRealTypeColorMarsfourUnitDiveIntoDimensionClear.jpg",
  "HGBuildDiversrerise-NAPFFX7E3EarthreeGundamGoldCoating.jpg",
  "HGBuildDiversrerise-NAPFFX7IIU7UravenGundamDiveIntoDimensionClear.jpg",
  "HGBuildDiversrerise-NATryAgeGundam.jpg",
  "HGBuildFighters-000BuildCustomGPBase.jpg",
  "HGBuildFighters-001BuildBooster.jpg",
  "HGBuildFighters-002AmazingBooster.jpg",
  "HGBuildFighters-003BuildBoosterMkII.jpg",
  "HGBuildFighters-004MeteorHopper.jpg",
  "HGBuildFighters-005MatsuriWeapon.jpg",
  "HGBuildFighters-006HyperGunplaBattleWeapons.jpg",
  "HGBuildFighters-007AmazingWeaponBinder.jpg",
  "HGBuildFighters-008UniverseBoosterPlavskyPowerGate.jpg",
  "HGBuildFighters-009K9DogPack.jpg",
  "HGBuildFighters-010GunplaBattleArmArms.jpg",
  "HGBuildFighters-011DarkMatterBooster.jpg",
  "HGBuildFighters-012SkullWeaponSet.jpg",
  "HGBuildFighters-013ValuablePod.jpg",
  "HGBuildFighters-015LightningBackWeaponSystem.jpg",
  "HGBuildFighters-016EzARMS.jpg",
  "HGBuildFighters-017MegaRideLauncher.jpg",
  "HGBuildFighters-018KurenaiWeapon.jpg",
  "HGBuildFighters-019MockArmySet.jpg",
  "HGBuildFighters-020LightningBackWeaponSystemMkII.jpg",
  "HGBuildFighters-021PortentFlyer.jpg",
  "HGBuildFighters-022BalldenArmArms.jpg",
  "HGBuildFighters-023GiantGatling.jpg",
  "HGBuildFighters-024JigenBuildKnucklesKaku.jpg",
  "HGBuildFighters-025JigenBuildKnucklesRound.jpg",
  "HGBuildFighters-026GyaEasternWeapons.jpg",
  "HGBuildFighters-027TheNorthernPod.jpg",
  "HGBuildFighters-031BallisticWeapons.jpg",
  "HGBuildFighters-033GalaxyBooster.jpg",
  "HGBuildFighters-034DiverGear.jpg",
  "HGBuildFighters-035ChangelingRifle.jpg",
  "HGBuildFighters-038SpinningBlaster.jpg",
  "HGBuildFighters-046HWSSVCustomWeaponSet.jpg",
  "HGBuildFighters-NAAmazingLevA.jpg",
  "HGBuildFighters-NAAmazingLevD.jpg",
  "HGBuildFighters-NAHJBuildWeaponCaledbwlchFeder.jpg",
  "HGBuildFighters-NAHJBuildWeaponCaledbwlchHonoo.jpg",
  "HGBuildFighters-NAMercuryLev.jpg",
  "HGBuildFighters-NAMercuryLevD.jpg",
  "HGBuildFighters-NAWingGundamZeroHonooCustomKit.jpg",
  "HGBuildFightesSDBF-001GATX105BFPBuildStrikeGundamFullPackage.jpg",
  "HGBuildFightesSDBF-002MS06RABZakuAmazing.jpg",
  "HGBuildFightesSDBF-003GX9999GundamXMaoh.jpg",
  "HGBuildFightesSDBF-004RX178BBuildGundamMkII.jpg",
  "HGBuildFightesSDBF-005KUMA03BeargguyIII.jpg",
  "HGBuildFightesSDBF-006XXXG01WfWingGundamFenice.jpg",
  "HGBuildFightesSDBF-007???SengokuAstrayGundam.jpg",
  "HGBuildFightesSDBF-008PPMS18EK„mpferAmazing.jpg",
  "HGBuildFightesSDBF-008PPMS18EK„mpferAmazing.jpg.z",
  "HGBuildFightesSDBF-009GATX105BSTStarBuildStrikeGundamPlavskyWing.jpg",
  "HGBuildFightesSDBF-010RGM79K9GMSniperK9.jpg",
  "HGBuildFightesSDBF-011NMX004QubeleyPapillon.jpg",
  "HGBuildFightesSDBF-012AC01MissSazabi.jpg",
  "HGBuildFightesSDBF-013PPGN001GundamExiaDarkMatter.jpg",
  "HGBuildFightesSDBF-014XMX9999CrossboneGundamMaoh.jpg",
  "HGBuildFightesSDBF-015MS07R35GoufR35.jpg",
  "HGBuildFightesSDBF-016PPGN001GundamAmazingExia.jpg",
  "HGBuildFightesSDBF-017XXXG01WfrGundamFeniceRinascita.jpg",
  "HGBuildFightesSDBF-019RGM237CPoweredGMCardigan.jpg",
  "HGBuildFightesSDBF-020LGZ91LightningGundam.jpg",
  "HGBuildFightesSDBF-021GundamEzSR.jpg",
  "HGBuildFightesSDBF-022KUMAFBeargguyF.jpg",
  "HGBuildFightesSDBF-023SD237WinningGundam.jpg",
  "HGBuildFightesSDBF-024AMX104GGRGyagya.jpg",
  "HGBuildFightesSDBF-025MSN001MMegaShiki.jpg",
  "HGBuildFightesSDBF-026PF783AGundamAmazingRedWarrior.jpg",
  "HGBuildFightesSDBF-027HiMock.jpg",
  "HGBuildFightesSDBF-028TBG011BTryBurningGundam.jpg",
  "HGBuildFightesSDBF-029RX93?2VHi?GundamVrabe.jpg",
  "HGBuildFightesSDBF-030SD237SStarWinningGundam.jpg",
  "HGBuildFightesSDBF-031GNW100PGundamPortent.jpg",
  "HGBuildFightesSDBF-032SDGGundam.jpg",
  "HGBuildFightesSDBF-033XXXG00W0CVWingGundamZeroHonoo.jpg",
  "HGBuildFightesSDBF-034GN9999TransientGundam.jpg",
  "HGBuildFightesSDBF-035XMX1CrossboneGundamX1FullClothTypeGBFT.jpg",
  "HGBuildFightesSDBF-036RXENDGundamTheEnd.jpg",
  "HGBuildFightesSDBF-037NK13JDenialGundam.jpg",
  "HGBuildFightesSDBF-038????GundamTryon3.jpg",
  "HGBuildFightesSDBF-039MS09R35DomR35.jpg",
  "HGBuildFightesSDBF-040MSZ006LGTLightningZetaGundam.jpg",
  "HGBuildFightesSDBF-041SD9071AKurenaiMushaRedWarriorAmazing.jpg",
  "HGBuildFightesSDBF-044SF01SuperFumina.jpg",
  "HGBuildFightesSDBF-047BN876ScrambleGundam.jpg",
  "HGBuildFightesSDBF-048KumaPBeargguyPPretty.jpg",
  "HGBuildFightesSDBF-049GNT0000SHIAGundam00ShiaQanT.jpg",
  "HGBuildFightesSDBF-050GN10000TransientGundamGlacier.jpg",
  "HGBuildFightesSDBF-051GSX40100LunagazerGundam.jpg",
  "HGBuildFightesSDBF-052KUMAPPPapagguy.jpg",
  "HGBuildFightesSDBF-055NK13SGundamSchwarzritter.jpg",
  "HGBuildFightesSDBF-056Chinagguy.jpg",
  "HGBuildFightesSDBF-059RGMGM79GMGM.jpg",
  "HGBuildFightesSDBF-060HG01HyperGyanko.jpg",
  "HGBuildFightesSDBF-061PF733BLGundamLightningBlackWarrior.jpg",
  "HGBuildFightesSDBF-062WF01WinningFumina.jpg",
  "HGBuildFightesSDBF-063CB9696GCTReversibleGundam.jpg",
  "HGBuildFightesSDBF-064GN006SACherudimGundamSAGATypeGBF.jpg",
  "HGBuildFightesSDBF-065GNX611TGStrikerGNX.jpg",
  "HGBuildFightesSDBF-066GATX105BGCBuildStrikeGalaxyCosmos.jpg",
  "HGBuildFightesSDBF-067LR01MrsLohengrinko.jpg",
  "HGBuildFightesSDBF-NAAGX04KirarasGerberaTetra.jpg",
  "HGBuildFightesSDBF-NAamazoncojpAZGundam.jpg",
  "HGBuildFightesSDBF-NABeargguyIII7ElevenColorVersion.jpg",
  "HGBuildFightesSDBF-NABeargguyIIIVer?DoubleHappiness.jpg",
  "HGBuildFightesSDBF-NABerryBerryBeargguyFFamily.jpg",
  "HGBuildFightesSDBF-NABG011BBuildBurningGundamFullColorPlatingVerSPSet.jpg",
  "HGBuildFightesSDBF-NABG011BBuildBurningGundamGoldVer.jpg",
  "HGBuildFightesSDBF-NABG011BBuildBurningGundamPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NABuildAkatsukiGundam.jpg",
  "HGBuildFightesSDBF-NAChinyagguy.jpg",
  "HGBuildFightesSDBF-NAEzSRMAXIMA.jpg",
  "HGBuildFightesSDBF-NAFuminaHoshinoTheGundamBaseColor.jpg",
  "HGBuildFightesSDBF-NAGATX105BFPBuildStrikeGundamFullPackagePlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NAGATX105BSTStarBuildStrikeGundamPlavskyParticleClearSpecialEventsVer.jpg",
  "HGBuildFightesSDBF-NAGATX105BSTStarBuildStrikeGundamPlavskyWingGoldVer.jpg",
  "HGBuildFightesSDBF-NAGATX105BSTStarBuildStrikeGundamVerRGSystem.jpg",
  "HGBuildFightesSDBF-NAGATX105TGTallStrikeGundamGlitter.jpg",
  "HGBuildFightesSDBF-NAGoldenBeargguyIII.jpg",
  "HGBuildFightesSDBF-NAGundamDynamesArmArms.jpg",
  "HGBuildFightesSDBF-NAGX999910GundamXJumaoh.jpg",
  "HGBuildFightesSDBF-NAHG02RRickDoGyanko.jpg",
  "HGBuildFightesSDBF-NAHJBuildWeaponCaletvwlchFeder.jpg",
  "HGBuildFightesSDBF-NAHJBuildWeaponCaletvwlchHonoo.jpg",
  "HGBuildFightesSDBF-NAKMKB01KamikiBurningGundamPlavskyParticleClear.jpg",
  "HGBuildFightesSDBF-NAKUMA03BeargguyIIITricolorPaint.jpg",
  "HGBuildFightesSDBF-NAM91GundamM91.jpg",
  "HGBuildFightesSDBF-NAMS07R35GoufR35PlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NAMSM07AAmazingZGok.jpg",
  "HGBuildFightesSDBF-NAMSN001GGillaShiki.jpg",
  "HGBuildFightesSDBF-NAMSN06SWWeissSinanju.jpg",
  "HGBuildFightesSDBF-NAMSZ006LGT3LightningZetaGundamAspros.jpg",
  "HGBuildFightesSDBF-NANeonBeargguy3000.jpg",
  "HGBuildFightesSDBF-NANeonBeargguyIII.jpg",
  "HGBuildFightesSDBF-NAPF783AGundamAmazingRedWarriorFullColorPlatedVer.jpg",
  "HGBuildFightesSDBF-NAPF783AGundamAmazingRedWarriorPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NAPPGN001GundamExiaDarkMatterTransAmMode.jpg",
  "HGBuildFightesSDBF-NARGM89GFGhostJeganF.jpg",
  "HGBuildFightesSDBF-NARGM89GMGhostJeganM.jpg",
  "HGBuildFightesSDBF-NARMS154WWeissBarzam.jpg",
  "HGBuildFightesSDBF-NARX139BANHambrabiSuban.jpg",
  "HGBuildFightesSDBF-NARX93?2IHi?GundamInflux.jpg",
  "HGBuildFightesSDBF-NARX93?2VAHi?GundamVrabeAmazingVerTheCrimsonComet.jpg",
  "HGBuildFightesSDBF-NASD237SStarWinningGundamPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NASD9071AKurenaiMushaRedWarriorAmazingPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NASF01SuperFuminaTheGundamBaseColor.jpg",
  "HGBuildFightesSDBF-NASuperFuminaAxisAngelverMkIIAxisImageColor.jpg",
  "HGBuildFightesSDBF-NASuperFuminaTitansMaidVer.jpg",
  "HGBuildFightesSDBF-NATBG011BTryBurningGundamFullColorCoatingVer.jpg",
  "HGBuildFightesSDBF-NATBG011BTryBurningGundamPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NAWF01WinningFuminaTheGundamBaseColor.jpg",
  "HGBuildFightesSDBF-NAWF02CCommandFumina.jpg",
  "HGBuildFightesSDBF-NAXMX1CrossboneGundamX1FullClothTypeGBFTPlatedClearVer.jpg",
  "HGBuildFightesSDBF-NAXXXG01WflGundamFeniceLiberta.jpg",
  "HGBuildFightesSDBF-NAYMS15SSGyanGyaGyan.jpg",
  "HGBuildFightesSDBF-NAYZR28SRFHEzSRFOXHOUND.jpg",
  "HGBuildFightesSDBF-NAZGMFX10AFreedomGundamPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NA???SengokuAstrayGundamPlavskyParticleClearVer.jpg",
  "HGBuildFightesSDBF-NA????GundamTryon3SpecialPlatedVer.jpg",
  "HGBuildFightesSDBF-NA????GundamDryonIII.jpg",
  "HGCE-Gelgoog-Menace-Lunamaria-Hawke.jpg",
  "HGCE-Immortal-Justice-Gundam.jpg",
  "HGCE-Rising-Freedom-Gundam.jpg",
  "HGFAEW-01WGundamZeroCustom.jpg",
  "HGFAEW-02TallgeeseIII.jpg",
  "HGFAEW-03GundamHArmsCustom.jpg",
  "HGFAEW-04SerpentCustom.jpg",
  "HGFAEW-05GundamDHellCustom.jpg",
  "HGFAEW-06GundamNataku.jpg",
  "HGFAEW-07GundamSandrockCustom.jpg",
  "HGG30th-711GP2014RX782GundamGoldInjectionColor7ElevenColorVer.jpg",
  "HGG30th-G30thGunplaStarterSetVol2.jpg",
  "HGG30th-G30thRX782GundamG30thANAOriginalColorVer.jpg",
  "HGG30th-G30thRX782GundamVerG30th.jpg",
  "HGG30th-G30thRX782GundamVerG30th7ElevenOriginalColorVer.jpg",
  "HGG30th-G30thRX782GundamVerG30thBMarkYoshidaPorterGunplaSpecialPackageVer.jpg",
  "HGG30th-G30thRX782GundamVerG30thClearColorVersion.jpg",
  "HGG30th-G30thRX782GundamVerG30thGreenTokyoGundamProject.jpg",
  "HGG30th-G30thRX782GundamVerG30thGundamTrailerTruckFullColorCoatingVer.jpg",
  "HGG30th-G30thRX782GundamVerG30thMitsuiSumitomoVisaCardVer.jpg",
  "HGG30th-G30thRX782GundamVerG30thPremiumGoldVer.jpg",
  "HGG30th-G30thRX782GundamVerG30thRG11GundamProject.jpg",
  "HGG30th-G30thRX783GundamVerG30th.jpg",
  "HGG30th-GFTRX782GundamVerGFT.jpg",
  "HGG30th-GFTRX782GundamVerGFT7ElevenOriginalColorVer.jpg",
  "HGG30th-SG50RX782GundamVerSG50.jpg",
  "hggto-Yoshikazu-Yasuhiko-artworks.jpg",
  "hggto-zaku-Yoshikazu-Yasuhikos-artworks.jpg",
  "HGHGEW-1XXXG01S2GundamNataku.jpg",
  "HGHGEW-2XXXG00W0WGundamZeroCustom.jpg",
  "HGHGEW-3OZ00MS2BTallgeeseIII.jpg",
  "HGHGEW-4XXXG01H2GundamHArmsCustom.jpg",
  "HGHGEW-5XXXG01D2GundamDHellCustom.jpg",
  "HGHGEW-6XXXG1SR2GundamSandrockCustom.jpg",
  "HGHGEW-7MMS01SerpentCustom.jpg",
  "HGHGEW-SXXXG00W0WGundamZeroCustomSpecialOperationType.jpg",
  "HGHGGBB-001MSBGH03GundamHelios.jpg",
  "HGHGGBB-002XXXG01L2GundamLivelanceHeaven.jpg",
  "HGHGGBB-003ZGMFX20APFGundamPerfectStrikeFreedom.jpg",
  "HGHGGBB-004JMF1337BBlazingGundam.jpg",
  "HGHGGBB-005ASWG084X4GundamBarbataurus.jpg",
  "HGHGGBB-006GNT0000SDVGundam00CommandQanT.jpg",
  "HGHGGBB-NAMBFP0SGundamAstrayRedFrameInversion.jpg",
  "HGHGGBB-NAXXXG00W0SKYWingGundamSkyZero.jpg",
  "HGHGGSEED-001MS06SCharsZakuII.jpg",
  "HGHGGSEED-002RTX65GuntankEarlyType.jpg",
  "HGHGGSEED-003MS06R1AZakuIIHighMobilityTypeGaiaMashCustom.jpg",
  "HGHGGSEED-004YMS07B0PrototypeGoufTacticalDemonstrator.jpg",
  "HGHGGSEED-005MS06R1AZakuIIHighMobilityTypeOrtegaCustom.jpg",
  "HGHGGSEED-006MobileWorkerMW01Model01LateTypeMash.jpg",
  "HGHGGSEED-007YMS08BDomTestType.jpg",
  "HGHGGSEED-008YMS03Waff.jpg",
  "HGHGGSEED-009MS05ZakuIDenimSlender.jpg",
  "HGHGGSEED-010RX7801NGundamLocalType.jpg",
  "HGHGGSEED-011RCX7602GuncannonFirstTypeIronCavalrySquadron.jpg",
  "HGHGGSEED-012MS04BuguRambaRal.jpg",
  "HGHGGSEED-013MS05SCharAznablesZakuI.jpg",
  "HGHGGSEED-014RCX7601GuncannonMobilityTestTypeFirepowerTestType.jpg",
  "HGHGGSEED-015MS05ZakuICharAznable.jpg",
  "HGHGGSEED-016MS06CZakuIITypeCTypeC5.jpg",
  "HGHGGSEED-020YMS11ActZakuKyciliasForces.jpg",
  "HGHGGSEED-021RX7801FSDGundamFSD.jpg",
  "HGHGGSEED-022RGM79HCGMGuardCustom.jpg",
  "HGHGGSEED-024MS06SCharsZakuIIRedCometVer.jpg",
  "HGHGGSEED-025MS06C6R6ZakuIITypeC6R6.jpg",
  "HGHGGSEED-026RX7802GundamGundamTheOriginVer.jpg",
  "HGHGGSEED-10GATX252ForbiddenGundam.jpg",
  "HGHGGSEED-11GATX370RaiderGundam.jpg",
  "HGHGGSEED-12MBFP02GundamAstrayRedFrame.jpg",
  "HGHGGSEED-13MBFP03GundamAstrayBlueFrame.jpg",
  "HGHGGSEED-14ZGMFX13AProvidenceGundam.jpg",
  "HGHGGSEED-15ZGMF515MobileCGUE.jpg",
  "HGHGGSEED-16ZGMFX10AFreedomGundamMETEORUnit.jpg",
  "HGHGGSEED-17ZGMFX56SàForceImpulseGundam.jpg",
  "HGHGGSEED-18ZGMF1000ZAKUWarrior.jpg",
  "HGHGGSEED-19ZGMFX24SChaosGundam.jpg",
  "HGHGGSEED-1GATX105AileStrikeGundam.jpg",
  "HGHGGSEED-1MBF02StrikeRougeIWSP.jpg",
  "HGHGGSEED-20ZGMFX88SGaiaGundam.jpg",
  "HGHGGSEED-21ZGMFX56SáSwordImpulseGundam.jpg",
  "HGHGGSEED-22ZGMF1000A1GunnerZAKUWarriorLunamariaHawkeCustom.jpg",
  "HGHGGSEED-23ZGMF1000A1GunnerZAKUWarrior.jpg",
  "HGHGGSEED-24ZGMFX23SSaviourGundam.jpg",
  "HGHGGSEED-25ZGMF1000ZAKUWarriorLiveConcertVersion.jpg",
  "HGHGGSEED-26ZGMFX31SAbyssGundam.jpg",
  "HGHGGSEED-27ZGMFX2000GOUFIgnitedHeineWestenflussCustom.jpg",
  "HGHGGSEED-28ZGMF1001MBlazeZAKUPhantomReyZaBurrelCustom.jpg",
  "HGHGGSEED-29ZGMF1017M2GINNTypeHighManeuver2.jpg",
  "HGHGGSEED-2GATX102DuelGundamAssaultShroud.jpg",
  "HGHGGSEED-2ZGMF1017MiguelsGINN.jpg",
  "HGHGGSEED-30ZGMFXX09TDOMTrooper.jpg",
  "HGHGGSEED-31ZGMFX2000GOUFIgnited.jpg",
  "HGHGGSEED-32ZGMFX19AJusticeGundam.jpg",
  "HGHGGSEED-33ZGMFX88SGaiaGundamAndrewWaldfeldCustom.jpg",
  "HGHGGSEED-34ZGMFX20AStrikeFreedomGundam.jpg",
  "HGHGGSEED-35ZGMFX666SLegendGundam.jpg",
  "HGHGGSEED-36ZGMFX42SDestinyGundam.jpg",
  "HGHGGSEED-37MVFM11CMurasameAndrewWaltfeldCustom.jpg",
  "HGHGGSEED-38ORB01ShiranuiAkatsukiGundam.jpg",
  "HGHGGSEED-39MVFM11CMurasame.jpg",
  "HGHGGSEED-3GATX303AegisGundam.jpg",
  "HGHGGSEED-3ZGMF1017MGINNHighManeuverType.jpg",
  "HGHGGSEED-40ORB01OowashiAkatsukiGundam.jpg",
  "HGHGGSEED-41GATX105EStrikeNoirGundam.jpg",
  "HGHGGSEED-42GATX103APVerdeBusterGundam.jpg",
  "HGHGGSEED-43GAT01A2R105SlaughterDagger.jpg",
  "HGHGGSEED-44GATX1022BluDuelGundam.jpg",
  "HGHGGSEED-45ZGMF1017GINNInsurgentType.jpg",
  "HGHGGSEED-46TMFA802W2KerberosBuCUEHound.jpg",
  "HGHGGSEED-47GSX401FWStargazerGundam.jpg",
  "HGHGGSEED-48TMFA802BuCUE.jpg",
  "HGHGGSEED-49UT1DCivilianAstrayDSSDCustom.jpg",
  "HGHGGSEED-4CAT1X13HyperionGundam.jpg",
  "HGHGGSEED-4GATX103BusterGundam.jpg",
  "HGHGGSEED-50ZGMF2000GOUFIgnitedYzakJouleCustom.jpg",
  "HGHGGSEED-51ZGMF1001MBlazeZAKUPhantomDearkaElsmanCustom.jpg",
  "HGHGGSEED-52ZGMF2000RudolfsGOUFIgnited.jpg",
  "HGHGGSEED-53TMFA802W2AlecsKerberosBuCUEHound.jpg",
  "HGHGGSEED-54ZGMF515XistsMobileCGUE.jpg",
  "HGHGGSEED-55TrojansGundamAstrayGreenFrame.jpg",
  "HGHGGSEED-56LeonssArmsAstrayPMCCustom.jpg",
  "HGHGGSEED-57MBFP03GundamAstrayBlueFrameSecondL.jpg",
  "HGHGGSEED-58MBFP02GundamAstrayRedFrameFlightUnit.jpg",
  "HGHGGSEED-59MBFP01Re2AMATUGundamAstrayGoldFrameAmatsuMina.jpg",
  "HGHGGSEED-5GATX207BlitzGundam.jpg",
  "HGHGGSEED-5YFX200CGUEDEEPArms.jpg",
  "HGHGGSEED-6GAT01A1AQMEX04GunbarrelDagger.jpg",
  "HGHGGSEED-6ZGMF1017MobileGINN.jpg",
  "HGHGGSEED-7YMFX000ADreadnoughtGundam.jpg",
  "HGHGGSEED-7ZGMFX10AFreedomGundam.jpg",
  "HGHGGSEED-8ZGMFX09AJusticeGundam.jpg",
  "HGHGGSEED-9GATX131CalamityGundam.jpg",
  "HGHGGSEED-NAFA782HeavyGundam.jpg",
  "HGHGGSEED-NAFA782HeavyGundamRolloutColor.jpg",
  "HGHGGSEED-NALightLiner.jpg",
  "HGHGGSEED-NALongRangeBeamRiflePrototype.jpg",
  "HGHGGSEED-NAMBFP01ReAMATUGundamAstrayGoldFrameAmatsu.jpg",
  "HGHGGSEED-NAMETEORUnit.jpg",
  "HGHGGSEED-NAMobileWorkerMW01Model01LateTypeRambaRal.jpg",
  "HGHGGSEED-NAMS04Bugu.jpg",
  "HGHGGSEED-NAMS05SCharAznablesZakuILimitedPackageVer.jpg",
  "HGHGGSEED-NAMS05ZakuIBlackTriStars.jpg",
  "HGHGGSEED-NAMS06CZakuIITypeCTypeC5TheatricalLimitedClearVer.jpg",
  "HGHGGSEED-NAMS06DZakuDesertType.jpg",
  "HGHGGSEED-NAMS06DZakuDesertTypeDoubleAntennaType.jpg",
  "HGHGGSEED-NAMS06KZakuCannon.jpg",
  "HGHGGSEED-NAMS06R1AZakuIIHighMobilityTypeBlackTriStarsMetallicVer.jpg",
  "HGHGGSEED-NAMS06RD4ZakuHighMobilityTestType.jpg",
  "HGHGGSEED-NAMS06SCharsZakuIIMetallic.jpg",
  "HGHGGSEED-NAMS06SZakuIICharCustomMetallicVer.jpg",
  "HGHGGSEED-NAMS06SZakuIIMARO17Ver.jpg",
  "HGHGGSEED-NAMS11ActZaku.jpg",
  "HGHGGSEED-NARCX7602GuncannonFirstTypeIronCavalrySquadronCommander.jpg",
  "HGHGGSEED-NARGC80SGMCannonSpaceAssaultType.jpg",
  "HGHGGSEED-NARGC80SGMCannonwithRocketBazooka.jpg",
  "HGHGGSEED-NARGM79HCGMGuardCustomwithE2BeamSprayGun.jpg",
  "HGHGGSEED-NARGM79KCGMInterceptCustomFellowBoosterEquipped.jpg",
  "HGHGGSEED-NARGM79VGMNightSeeker.jpg",
  "HGHGGSEED-NARTX65GuntankEarlyTypeTheatricalLimitedClearVer.jpg",
  "HGHGGSEED-NARX7802GundamGundamTheOriginVerClearColor.jpg",
  "HGHGGSEED-NARX7802GundamRolloutColorGundamTheOriginVer.jpg",
  "HGHGGSEED-NARX7802GundamYoshikazuYasuhikoMOBILESUITGUNDAMTHEORIGINExhibitionEdition.jpg",
  "HGHGGSEED-NAYMS07A0PrototypeGoufMobilityDemonstratorSandColorVer.jpg",
  "HGHGGSEED-NAZGMFX20AStrikeFreedomGundamVerGFT.jpg",
  "HGHGGSEED-NAZGMFX20AStrikeFreedomGundamVerGFT7ElevenVer.jpg",
  "HGHGGSEED-R01GATX105AileStrikeGundam.jpg",
  "HGHGGSEED-R02GATX102DuelGundamAssaultShroud.jpg",
  "HGHGGSEED-R03GATX103BusterGundam.jpg",
  "HGHGGSEED-R04GATX207BlitzGundam.jpg",
  "HGHGGSEED-R05GATX303AegisGundam.jpg",
  "HGHGGSEED-R06ZGMF1017MobileGINN.jpg",
  "HGHGGSEED-R07ZGMF515MobileCGUE.jpg",
  "HGHGGSEED-R08GATX131CalamityGundam.jpg",
  "HGHGGSEED-R09GATX252ForbiddenGundam.jpg",
  "HGHGGSEED-R10GATX370RaiderGundam.jpg",
  "HGHGGSEED-R11TMFA803LaGOWE.jpg",
  "HGHGGSEED-R12TMFA802BuCUE.jpg",
  "HGHGGSEED-R13ZGMFX13AProvidenceGundam.jpg",
  "HGHGGSEED-R14ZGMFX09AJusticeGundam.jpg",
  "HGHGGSEED-R15ZGMFX10AFreedomGundam.jpg",
  "HGHGGSEED-R16MBFM1M1Astray.jpg",
  "HGHGGSEED-R17GATX105AQMEYM1PerfectStrikeGundam.jpg",
  "HGHGUC-001RX772Guncannon.jpg",
  "HGHGUC-002YMS15Gyan.jpg",
  "HGHGUC-003AMX011SZakuIIICustom.jpg",
  "HGHGUC-004AMX004Qubeley.jpg",
  "HGHGUC-005MSN00100HyakuShiki.jpg",
  "HGHGUC-006MSM07Z'Gok.jpg",
  "HGHGUC-007RX75Guntank.jpg",
  "HGHGUC-008MSM03Gogg.jpg",
  "HGHGUC-009MS07BGouf.jpg",
  "HGHGUC-010RMS099RickDias.jpg",
  "HGHGUC-011AMX0042QubeleyMkII.jpg",
  "HGHGUC-012RMS106HiZack.jpg",
  "HGHGUC-013RX78GP01GundamGP01.jpg",
  "HGHGUC-014AMX011ZakuIII.jpg",
  "HGHGUC-015AMX107Bawoo.jpg",
  "HGHGUC-016MS14FGelgoogMarine.jpg",
  "HGHGUC-017MS09FDomTropen.jpg",
  "HGHGUC-018RX78GP01FbGundamGP01Fb.jpg",
  "HGHGUC-019MSM07SZ'GokCommanderTypeCharAznablecustom.jpg",
  "HGHGUC-020RGM79GM.jpg",
  "HGHGUC-021RX782Gundam.jpg",
  "HGHGUC-022MSN02Zeong.jpg",
  "HGHGUC-023MSA0011SGundam.jpg",
  "HGHGUC-024RMS141Xekueins.jpg",
  "HGHGUC-025RX78GP03SGundamGP03S.jpg",
  "HGHGUC-026MS14FsGelgoogMarineCimaGarahaucustom.jpg",
  "HGHGUC-027MS09FDomTropenKimberliteForcescolors.jpg",
  "HGHGUC-028RX78GP03GundamGP03Dendrobium.jpg",
  "HGHGUC-029MSA0011ExtExSGundam.jpg",
  "HGHGUC-030RX178GundamMkIITitanscolors.jpg",
  "HGHGUC-031AMX107BawooMassProductioncolors.jpg",
  "HGHGUC-032MS06SZakuIICommanderTypeCharAznablecustom.jpg",
  "HGHGUC-033RMS099RickDiasQuattroBajeenacustom.jpg",
  "HGHGUC-034MS06FsZakuIITypeFSGarmaZabicustom.jpg",
  "HGHGUC-035FXA05DRX178SuperGundam.jpg",
  "HGHGUC-036PMX003TheO.jpg",
  "HGHGUC-037MSM03CHyGogg.jpg",
  "HGHGUC-038RGM79DGMColdDistrictsType.jpg",
  "HGHGUC-039MSM07EZ'GokExperiment.jpg",
  "HGHGUC-040MS06FZakuII.jpg",
  "HGHGUC-041MSZ006ZetaGundam.jpg",
  "HGHGUC-042ORX005Gaplant.jpg",
  "HGHGUC-043MS09R2RickDomII.jpg",
  "HGHGUC-044RX77DGuncannonMassProductionType.jpg",
  "HGHGUC-045MS14JGGelgoogJ„ger.jpg",
  "HGHGUC-045MS14JGGelgoogJ„ger.jpg.z",
  "HGHGUC-046RGM79GGMCommand.jpg",
  "HGHGUC-047RX78NT1GundamNT1.jpg",
  "HGHGUC-048HyakuShikiMegaBazookaLauncher.jpg",
  "HGHGUC-049MRX009PsychoGundam.jpg",
  "HGHGUC-050GArmorGFighterRX782Gundam.jpg",
  "HGHGUC-051RGM79GGMCommandSpace.jpg",
  "HGHGUC-052RMS108Marasai.jpg",
  "HGHGUC-053RX178GundamMkIIFlyingarmor.jpg",
  "HGHGUC-054NRX044Asshimar.jpg",
  "HGHGUC-055RMS106HiZackEarthFederationForcecolors.jpg",
  "HGHGUC-056RX1211GundamTR1HazelCustom.jpg",
  "HGHGUC-057RX1212AGundamTR1AdvancedHazel.jpg",
  "HGHGUC-058RX110Gabthley.jpg",
  "HGHGUC-059MS09DomMS09RRickDom.jpg",
  "HGHGUC-060PMX001PalaceAthene.jpg",
  "HGHGUC-061MSA005Methuss.jpg",
  "HGHGUC-062AMX003GazaCHamanKarnCustom.jpg",
  "HGHGUC-063AMX003GazaC.jpg",
  "HGHGUC-064MS05BZakuI.jpg",
  "HGHGUC-065EMS10Zudah.jpg",
  "HGHGUC-066RX78GP02AGundamGP02A.jpg",
  "HGHGUC-067RGM79PoweredGM.jpg",
  "HGHGUC-068MS05BZakuIBlackTriStarsType.jpg",
  "HGHGUC-069RX1212GundamTR1HazelII.jpg",
  "HGHGUC-070MS14SGelgoogCharAznableCustom.jpg",
  "HGHGUC-071MS05LZakuISniperType.jpg",
  "HGHGUC-072RGM79FPGMStriker.jpg",
  "HGHGUC-073ORX005GaplantTR5Hrairoo.jpg",
  "HGHGUC-074RGM79QGMQuel.jpg",
  "HGHGUC-075RX78GP02AGundamGP02ATypeMLRS.jpg",
  "HGHGUC-076MS14AGelgoogMS14CGelgoogCannon.jpg",
  "HGHGUC-077RX79BD2BlueDestinyUnit2.jpg",
  "HGHGUC-078MSM04Acguy.jpg",
  "HGHGUC-079RX79GGundamGroundType.jpg",
  "HGHGUC-080RX79BD1BlueDestinyUnit1.jpg",
  "HGHGUC-081MSM10Zock.jpg",
  "HGHGUC-082RX79BD3BlueDestinyUnit3.jpg",
  "HGHGUC-083MSN03JagdDogaGyuneiGussCustom.jpg",
  "HGHGUC-084MSN03JagdDogaQuessParayaCustom.jpg",
  "HGHGUC-085RGZ91ReGZ.jpg",
  "HGHGUC-086RX93?Gundam.jpg",
  "HGHGUC-087MS06FZZakuIIFZ.jpg",
  "HGHGUC-088MSN04Sazabi.jpg",
  "HGHGUC-089MS18EK„mpfer.jpg",
  "HGHGUC-089MS18EK„mpfer.jpg.z",
  "HGHGUC-090MS09RIIRickDomIIColonyAttackColors.jpg",
  "HGHGUC-091AMS119GearaDoga.jpg",
  "HGHGUC-092AMS119GearaDogaRezinSchnyderCustom.jpg",
  "HGHGUC-093?GundamHWS.jpg",
  "HGHGUC-094RMS099BSchuzrumDias.jpg",
  "HGHGUC-095RX93?2Hi?Gundam.jpg",
  "HGHGUC-096RMS119EWACZack.jpg",
  "HGHGUC-097RGM89Jegan.jpg",
  "HGHGUC-098FA783FullArmorGundam7th.jpg",
  "HGHGUC-099NZ666Kshatriya.jpg",
  "HGHGUC-100RX0UnicornGundamDestroyMode.jpg",
  "HGHGUC-101RX0UnicornGundamUnicornMode.jpg",
  "HGHGUC-102AMS129GearaZulu.jpg",
  "HGHGUC-103RGZ95ReZEL.jpg",
  "HGHGUC-104RGM89SStarkJegan.jpg",
  "HGHGUC-105MS06F2ZakuIIF2ZeonVersion.jpg",
  "HGHGUC-106D50CLotoTwinSet.jpg",
  "HGHGUC-107MS06F2ZakuIIF2EFSFVersion.jpg",
  "HGHGUC-108RGZ95CReZELCommanderType.jpg",
  "HGHGUC-109GX9900GundamX.jpg",
  "HGHGUC-110GF13017NJIIGGundam.jpg",
  "HGHGUC-111MSZ010??Gundam.jpg",
  "HGHGUC-112AMS129GearaZuluAngeloSauperUse.jpg",
  "HGHGUC-113RGM79CGMTypeC.jpg",
  "HGHGUC-114RB79BallTwinSet.jpg",
  "HGHGUC-115MSN001A1DeltaPlus.jpg",
  "HGHGUC-116MSN06SSinanju.jpg",
  "HGHGUC-117MS07B3GoufCustom.jpg",
  "HGHGUC-118GX9900DVGundamXDivider.jpg",
  "HGHGUC-119GF13050NSWNobellGundam.jpg",
  "HGHGUC-120RGM79NGMCustom.jpg",
  "HGHGUC-121ExtremeGundam.jpg",
  "HGHGUC-122AMS129GearaZuluGuardsType.jpg",
  "HGHGUC-123RGM89DeJeganECOASType.jpg",
  "HGHGUC-124AMX009DreissenUnicornVer.jpg",
  "HGHGUC-125RGC83GMCannonII.jpg",
  "HGHGUC-126RGM86RGMIII.jpg",
  "HGHGUC-127GF13017NJ"
];

/**
 * Fetch Gundam images from GunplaDB by trying multiple grade/keyword patterns
 */
export async function fetchGundamImages(
  modelName: string,
  grade?: GundamGrade
): Promise<GunplaDBResponse & { imageOptions?: string[] }> {
  try {
    // Clean and normalize the model name
    const cleanName = modelName
      .toLowerCase()
      .replace(/[^\w\s-]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    // Extract keywords (min length = 3)
    const keywords = cleanName.split(' ').filter(word => word.length > 2);

    // Grade → prefixes
    const gradeMap: Record<string, string[]> = {
      'High Grade (HG)': ['HG', 'HGUC', 'HGHGUC'],
      'Real Grade (RG)': ['RG'],
      'Master Grade (MG)': ['MG'],
      'Perfect Grade (PG)': ['PG'],
      'Super Deformed (SD)': ['SD'],
      'No Grade': ['NG'],
      'Other': ['HG', 'RG', 'MG']
    };

    const gradePrefixes = grade ? gradeMap[grade] || ['HG'] : ['HG', 'RG', 'MG', 'PG'];

    // Generate possible URLs
    const possibleUrls: string[] = [];
    for (const gradePrefix of gradePrefixes) {
      for (const keyword of keywords) {
        const patterns = [
          `${gradePrefix}${keyword.toUpperCase()}`,
          `${gradePrefix}-${keyword.toUpperCase()}`,
          `${gradePrefix}${keyword.charAt(0).toUpperCase() + keyword.slice(1)}`,
          `${gradePrefix}UC-${keyword.toUpperCase()}`,
          `${gradePrefix}IBO-${keyword.toUpperCase()}`,
          `${gradePrefix}SEED-${keyword.toUpperCase()}`,
          `${gradePrefix}00-${keyword.toUpperCase()}`,
          `${gradePrefix}W-${keyword.toUpperCase()}`
        ];

        for (const pattern of patterns) {
          possibleUrls.push(`https://cdn.gunpladb.net/${pattern}.jpg`);
        }
      }

      // Try combined keywords
      if (keywords.length > 1) {
        const combinedKeyword = keywords.join('');
        possibleUrls.push(`https://cdn.gunpladb.net/${gradePrefix}${combinedKeyword.toUpperCase()}.jpg`);
        possibleUrls.push(`https://cdn.gunpladb.net/${gradePrefix}-${combinedKeyword.toUpperCase()}.jpg`);
      }
    }

    // Deduplicate
    const uniqueUrls = [...new Set(possibleUrls)];

    // Validate URLs (limit 20 checks)
    const validUrls: string[] = [];
    for (const url of uniqueUrls.slice(0, 20)) {
      const isValid = await validateImageUrl(url);
      if (isValid) validUrls.push(url);
    }

    if (validUrls.length > 0) {
      return {
        success: true,
        imageUrl: validUrls[0],
        imageOptions: validUrls
      };
    }

    // Fallback patterns
    const fallbackPatterns = [
      `HGHGUC-${modelName.replace(/\s+/g, '').toUpperCase()}`,
      `RG${modelName.replace(/\s+/g, '').toUpperCase()}`,
      `MG${modelName.replace(/\s+/g, '').toUpperCase()}`
    ];

    for (const pattern of fallbackPatterns) {
      const fallbackUrl = `https://cdn.gunpladb.net/${pattern}.jpg`;
      const isValid = await validateImageUrl(fallbackUrl);
      if (isValid) {
        return { success: true, imageUrl: fallbackUrl };
      }
    }

    return { success: false, error: 'No images found for this model and grade combination' };
  } catch (error) {
    console.error('Error fetching Gundam image:', error);
    return { success: false, error: 'Failed to fetch image from GunplaDB' };
  }
}

/**
 * Legacy wrapper for backward compatibility
 */
export async function fetchGundamImage(modelName: string): Promise<GunplaDBResponse> {
  const result = await fetchGundamImages(modelName);
  return {
    success: result.success,
    imageUrl: result.imageUrl,
    error: result.error
  };
}

/**
 * Validate that an image URL is accessible
 */
export async function validateImageUrl(url: string): Promise<boolean> {
  try {
    const response = await fetch(url, { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
}