#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const IN = path.resolve(process.cwd(), 'scrapers', 'out', 'products_upsert.sql');
const OUT = path.resolve(process.cwd(), 'scrapers', 'out', 'products_per_row_update_titles.sql');

function titleCase(str) {
  return str.split(/\s+/).map(w => {
    if (!w) return '';
    // keep short acronyms all caps later
    return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
  }).join(' ').trim();
}

function postProcess(title) {
  // Uppercase common acronyms and roman numerals
  // replace roman numerals II, III, IV, V etc
  title = title.replace(/\b(I{2,3}|IV|V|VI|VII|VIII|IX|X)\b/gi, m => m.toUpperCase());
  // Uppercase known acronyms (word boundaries)
  title = title.replace(/\b(mg|hg|rg|pg|sd|rx|uc)\b/gi, m => m.toUpperCase());
  return title;
}

function deriveTitleFromUrl(url) {
  if (!url) return '';
  try {
    const u = new URL(url);
    const parts = u.pathname.split('/').filter(Boolean);
    let seg = parts.length ? parts[parts.length - 1] : '';
    seg = decodeURIComponent(seg);
    seg = seg.replace(/\.(html?|php|asp|aspx)$/i, '');
    seg = seg.replace(/[-_]+/g, ' ');
    seg = seg.replace(/\s+/g, ' ').trim();
    let t = titleCase(seg);
    t = postProcess(t);
    return t;
  } catch (e) {
    // fallback: try regex extraction
    const m = url.match(/[^\/]+(?=\/?$)/);
    let seg = m ? m[0] : url;
    try { seg = decodeURIComponent(seg); } catch(e) {}
    seg = seg.replace(/\.(html?|php|asp|aspx)$/i, '');
    seg = seg.replace(/[-_]+/g, ' ');
    seg = seg.replace(/\s+/g, ' ').trim();
    let t = titleCase(seg);
    t = postProcess(t);
    return t;
  }
}

// read input
if (!fs.existsSync(IN)) {
  console.error('Input file not found:', IN);
  process.exit(2);
}

const raw = fs.readFileSync(IN, 'utf8');
const lines = raw.split(/\r?\n/);

// skip header if present (first line starts with "id" and tabs)
let start = 0;
if (lines[0] && lines[0].toLowerCase().includes('"id"') && lines[0].toLowerCase().includes('"url"')) {
  start = 1;
}

const updates = [];

for (let i = start; i < lines.length; i++) {
  let line = lines[i];
  if (!line) continue;
  line = line.trim();
  // skip fenced code markers (```sql or ```)
  if (line.startsWith('```')) continue;
  // only process lines that look like data rows starting with a quoted id
  if (!line.startsWith('"')) continue;
  // match quoted fields: "..." (fields may contain double quotes escaped? assume not)
  // Try TSV split first (the products_upsert.sql is exported as TSV with quoted fields)
  let id = '';
  let url = '';
  if (line.indexOf('\t') !== -1) {
    const cols = line.split('\t').map(c => c.trim());
    // remove surrounding quotes if present
    const unquote = s => (s && s[0] === '"' && s[s.length-1] === '"') ? s.slice(1, -1) : s;
    if (cols.length >= 3) {
      id = unquote(cols[0]);
      url = unquote(cols[2]);
    }
  }
  // Fallback: regex match quoted fields
  if (!id || !url) {
    const matches = line.match(/"([^"]*)"/g);
    if (matches && matches.length >= 3) {
      const fields = matches.map(s => s.slice(1, -1));
      id = fields[0];
      url = fields[2];
    }
  }
  if (!id || !url) continue;
  const title = deriveTitleFromUrl(url) || '';
  const safe = title.replace(/'/g, "''");
  updates.push({ id, title: safe });
}

// write output
const header = `-- products_per_row_update_titles.sql
-- Generated by scripts/generate_per_row_updates_from_upsert.mjs
-- This file contains literal per-row UPDATE statements. Review before running.
BEGIN;
\n`;

const footer = `\nCOMMIT;\n-- Total updates: ${updates.length}\n`;

const body = updates.map(u => `UPDATE products SET title = '${u.title}' WHERE id = '${u.id}';`).join('\n');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body + footer, 'utf8');

console.log('Wrote', OUT, 'with', updates.length, 'updates');
